GET http://localHost:4000/users

###

POST http://localHost:4000/users/new
Content-Type: application/json

{
    "firstName": "Jade3",
    "lastName": "Terry",
    "email": "AndersonJade18@gmail.com",
    "password": "Lehicheer18",
    "subscribed": true
}

###

DELETE http://localHost:4000/users/delete/

##

# Turn Off Subscriptions
PUT http://localHost:4000/users/subscriptionOff/

###
# Turn On Subscriptions
PUT http://localHost:4000/users/subscriptionOn/